Feature/eth/rpc
NoirHQ/smite pull request #59
Opened 2022-02-11 05:02 UTC by code0xff

2022-02-11 06:32 UTC, xedonman commented on src/eth/rpc/rpc_test.cpp
> +    CHECK_THROWS_WITH(rpc::check_send_raw_tx(params), "too many arguments, want at most 1");
Could you add positive test with CHECK_NO_THROW()?

2022-02-11 07:21 UTC, conr2d commented
It would be better to use the more meaningful title for PR.

2022-02-11 08:38 UTC, conr2d requested changes

2022-02-11 08:38 UTC, conr2d commented on src/eth/rpc/rpc.cpp
> +#include <appbase/application.hpp>
```suggestion
```

Isn't this included by `<eth/rpc/rpc.h>`?

2022-02-11 08:38 UTC, conr2d commented on src/eth/rpc/rpc.cpp
> +#include <noir/common/hex.h>
It is mandatory for ethereum hex strings to start with `0x` prefix, but `noir::from_hex` can convert hex strings without the prefix. We may need the common conversion function that requires the length of even number and no prefix, but specialized conversion for specific protocol.

2022-02-11 08:38 UTC, conr2d commented on src/eth/rpc/rpc.cpp
> +void rpc::check_send_raw_tx(const fc::variant& req) {
This implementation can be used without activating ethereum RPC emulation. It would be better to put this separated class like `eth::api` and connect rpc with api.

2022-02-11 08:38 UTC, conr2d commented on src/eth/rpc/tx.h
> +  uint256_t v;
```suggestion
  uint64_t v;
```
Isn't 64bit enough this time?

2022-02-11 08:38 UTC, conr2d commented on src/eth/rpc/rpc.h
> +  eth::uint256_t tx_fee_cap;
```suggestion
uint256_t tx_fee_cap;
```
I think this works without explicit `eth::`.

2022-02-11 08:38 UTC, conr2d commented on src/eth/rpc/tx.h
> +    return gas_price * gas;
To prevent overflow, we may need to use checked_uint256_t for this kind of calculation or perform manual check.

2022-02-11 08:38 UTC, conr2d commented on src/eth/rpc/rpc.cpp
> +std::string rpc::send_raw_tx(const std::string& rlp) {
This implementation can be used without activating ethereum RPC emulation. It would be better to put this separated class like eth::api and connect rpc with api.

2022-02-15 14:30 UTC, conr2d approved these changes

2022-02-16 01:45 UTC, merged